version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/core:/app/core
      - ./backend/files:/app/files
      - ./backend/manage.py:/app/manage.py
      - ./backend/requirements.txt:/app/requirements.txt
      - ./backend/start.sh:/app/start.sh
      - ./backend/cleanup.sh:/app/cleanup.sh
      - backend_media:/app/media
      - ./data:/app/data
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=your-secret-key-here

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  backend_media: 