# Generated by Django 4.2.20 on 2025-04-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_hash',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
