# Generated by Django 4.2.20 on 2025-05-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_file_hash'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='files_metadata',
        ),
    ]
