# Generated by Django 4.2.20 on 2025-05-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='original_filename',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['original_filename'], name='files_metad_origina_d674b5_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_type'], name='files_metad_file_ty_29c26f_idx'),
        ),
    ]
