# Generated by Django 4.2.20 on 2025-05-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_reference'),
        ('files', '0004_alter_file_original_filename_and_more'),
    ]

    operations = [
    ]
