# Generated by Django 4.2.20 on 2025-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_merge_20250502_1259'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='files_metad_origina_d674b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='files_metad_file_ty_29c26f_idx',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_filename',
            field=models.CharField(max_length=255),
        ),
    ]
