# Generated by Django 4.2.20 on 2025-05-02 13:13

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_remove_file_files_metad_origina_d674b5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.file_upload_path),
        ),
    ]
