# Generated by Django 4.2.20 on 2025-05-02 16:14

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_finalize_stored_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='stored_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_records', to='files.storedfile'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='file',
            field=models.FileField(upload_to=files.models.file_upload_path),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='file_hash',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='reference_count',
            field=models.IntegerField(default=0),
        ),
    ]
